### ISSUE TITLE
The project.nvim plugin does not work as expected

### ISSUE THREAD

**Issue by fangying** [ofseed/nvim#3]
When I try to launch the projects using `<leader>fp` I can see the telescope projects floating window but no project is listed there.

So I think there must be something wrong with the project plugin, hope it can be fixed since it is quite a handy plugin that can help improve the efficiency.

**Comment by ofseed** [comment]
You may check the home page of these plugins first when you have problems.

The README of [telescope-project](https://github.com/nvim-telescope/telescope-project.nvim) explicitly mentioned a set of keymap to create and delete your project, which means there will not be any projects listed unless you created them manually.

If you want something like recent projects like vscode, you should use [neovim-session-manager](https://github.com/Shatur/neovim-session-manager) instead, keymap prefix is x in my configuration file.

**Comment by fangying** [comment]
Thanks.

There are two project plugins configured, [telescope-project.nvim](https://github.com/nvim-telescope/telescope-project.nvim) and [project.nvim](https://github.com/ahmedkhalf/project.nvim) in the [plugins.lua](https://github.com/ofseed/nvim/tree/main/lua/plugins.lua) file, [telescope-project.nvim](https://github.com/nvim-telescope/telescope-project.nvim) has mentioned one should first create a project however [project](https://github.com/ahmedkhalf) does not. And [lua/core/project.lua](https://github.com/ofseed/nvim/tree/main/lua/core/project.lua) has set `munual_mode` to `false`. 

So I had thought it could create projects automatically like vscode does :smiley:
