### ISSUE TITLE
插件安装都成功了，但是...

### ISSUE THREAD

**Issue by ahuxjz** [ofseed/nvim#4]
插件安装都成功了，但是c语言语法没有高亮且lsp 代码补全如何使用？有时候咋没补全信息。

**Comment by ofseed** [comment]
`:LspInstall` 可以安装对应LSP server，不太建议完全的新手使用

**Comment by ahuxjz** [comment]
![image](https://user-images.githubusercontent.com/44185528/199157061-d2b695a7-a973-4464-820d-0771c3f385b6.png)

**Comment by ahuxjz** [comment]
已经安装上了，c语言为啥还不高亮呢

**Comment by ofseed** [comment]
高亮是由treesitter决定的。如果你没有忽略错误，我的配置会自动确保c的treesitter parser会安装上，也会自动应用。
否则就是后缀名不对导致 `:h filetype` 不正确而没有应用高亮

**Comment by ahuxjz** [comment]
Error running notification service: ...art/nvim-notify/lua/notify/service/buffer/highlights.lua:153: Invalid buffer id

**Comment by ahuxjz** [comment]
![image](https://user-images.githubusercontent.com/44185528/199166737-41118815-6799-4688-8acf-86cfb5768b92.png)

**Comment by ahuxjz** [comment]
利用PackerSync已经安装了所有的插件，但在打开.c文件时候会出现该错误

**Comment by ofseed** [comment]
这个错误是你缺少github-cli，但是它与 `.c` 文件没有关系
