### ISSUE TITLE
Could you share your kitty.conf file?

### ISSUE THREAD

**Issue by tan-wei** [ofseed/nvim#6]
It seems that you use Kitty as your terminal. Could you share the kitty.conf? As I know, only Kitty works perfect with ident-blankline.nvim (with `modify_font`). Thanks very much.

**Comment by ofseed** [comment]
https://gist.github.com/ofseed/51e7f5b6bafee31bf8574a644662bb2e

**Comment by tan-wei** [comment]
Thanks! Glory glory Halleluja!
